const express = require("express");
const router = express.Router();
const achievementController = require("../controllers/achievementController");

/**
 * @swagger
 * tags:
 *   name: Achievements
 *   description: Endpoints for achievement management
 */

/**
 * @swagger
 * components:
 *   schemas:
 *     Achievement:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           description: Unique ID generated by MongoDB
 *         name:
 *           type: string
 *           description: Name of the achievement
 *         description:
 *           type: string
 *           description: Description of the achievement
 *         requirements:
 *           type: object
 *           additionalProperties:
 *             type: string
 *       example:
 *         _id: "661feaf8bc3e2a9c1234abcd"
 *         name: "First Event"
 *         description: "Attend your first event"
 *         requirements:
 *           attendedEvents: ">=1"
 */

/**
 * @swagger
 * /api/achievements:
 *   get:
 *     summary: Get all achievements
 *     tags: [Achievements]
 *     responses:
 *       200:
 *         description: List of achievements
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Achievement'
 */
router.get("/", achievementController.getAchievements);

/**
 * @swagger
 * /api/achievements/getById/{id}:
 *   get:
 *     summary: Get achievement by ID
 *     tags: [Achievements]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *     responses:
 *       200:
 *         description: Achievement found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Achievement'
 *       404:
 *         description: Achievement not found
 */
router.get("/getById/:id", achievementController.getAchievementById);

/**
 * @swagger
 * /api/achievements/user/{userId}:
 *   get:
 *     summary: Get all achievements of a user
 *     tags: [Achievements]
 *     parameters:
 *       - in: path
 *         name: userId
 *         schema:
 *           type: string
 *         required: true
 *         description: User ID
 *     responses:
 *       200:
 *         description: List of achievements obtained by the user
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Achievement'
 *       404:
 *         description: The user has no achievements
 */
router.get("/user/:userId", achievementController.getAchievementsByUserId);

module.exports = router;
