const express = require("express");
const router = express.Router();
const cityController = require("../controllers/cityController");
const authenticateJWT = require('../middlewares/authenticateJWT');
const { check, validationResult } = require('express-validator');  // Para validaciones

/**
 * @swagger
 * tags:
 *   name: Cities
 *   description: Endpoints for city management
 */

/**
 * @swagger
 * components:
 *   schemas:
 *     City:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           description: Unique ID generated by MongoDB
 *         city_name:
 *           type: string
 *           description: Name of the city
 *         location:
 *           type: object
 *           properties:
 *             type:
 *               type: string
 *               enum: ['Point']
 *             coordinates:
 *               type: array
 *               items:
 *                 type: number
 *               example: [2.3522, 48.8566]
 *       example:
 *         _id: "60c72b2f9b1e8a001c8e4d2a"
 *         name: "Paris"
 *         location:
 *           type: "Point"
 *           coordinates: [2.3522, 48.8566]
 *         avg_rating: 4.8
 *         total_ratings: 214
 *         type: "CITY"
 */

/**
 * @swagger
 * /api/cities:
 *   get:
 *     summary: Get all cities
 *     tags: [Cities]
 *     parameters:
 *       - in: query
 *         name: limit
 *         schema:
 *           type: number
 *         description: "Result limit (default: 10)"
 *     responses:
 *       200:
 *         description: List of cities
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/City'
 */
router.get("/", cityController.getCities);

/**
 * @swagger
 * /api/cities/nearby:
 *   get:
 *     summary: Get nearby cities
 *     tags: [Cities]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: lng
 *         schema:
 *           type: number
 *         required: true
 *       - in: query
 *         name: lat
 *         schema:
 *           type: number
 *         required: true
 *       - in: query
 *         name: maxDistance
 *         schema:
 *           type: number
 *     responses:
 *       200:
 *         description: List of nearby cities
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/City'
 */
router.get("/nearby", authenticateJWT, cityController.getNearbyCities);

/**
 * @swagger
 * /api/cities/{id}:
 *   get:
 *     summary: Get city by ID
 *     tags: [Cities]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *     responses:
 *       200:
 *         description: City found
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/City'
 *       404:
 *         description: City not found
 */
router.get("/:id", cityController.getCityById);

module.exports = router;
