const express = require("express");
const router = express.Router();
const restaurantController = require("../controllers/restaurantController");

/**
 * @swagger
 * tags:
 *   name: Restaurants
 *   description: Endpoints for restaurant management, including CRUD operations and proximity search.
 */

/**
 * @swagger
 * components:
 *   schemas:
 *     Restaurant:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           description: Unique restaurant ID generated by MongoDB.
 *         name:
 *           type: string
 *           description: Name of the restaurant.
 *         location:
 *           type: object
 *           properties:
 *             type:
 *               type: string
 *               enum: ['Point']
 *               description: Geospatial data type.
 *             coordinates:
 *               type: array
 *               items:
 *                 type: number
 *               description: Geographic coordinates [longitude, latitude].
 *         country_code:
 *           type: number
 *           description: Country code.
 *         city:
 *           type: string
 *           description: City where the restaurant is located.
 *         address:
 *           type: string
 *           description: Restaurant address.
 *         cuisines:
 *           type: string
 *           description: Types of cuisine offered.
 *         average_cost_for_two:
 *           type: number
 *           description: Average cost for two people.
 *         currency:
 *           type: string
 *           description: Currency used.
 *         has_table_booking:
 *           type: boolean
 *           description: Indicates whether the restaurant allows table bookings.
 *         has_online_delivery:
 *           type: boolean
 *           description: Indicates whether the restaurant offers online delivery.
 *         aggregate_rating:
 *           type: number
 *           description: Aggregate rating of the restaurant.
 *         votes:
 *           type: number
 *           description: Number of votes received.
 *       example:
 *         _id: "60c72b2f9b1e8a001c8e4d2a"
 *         name: "Le Petit Souffle"
 *         location:
 *           type: "Point"
 *           coordinates: [121.027535, 14.565443]
 *         country_code: 162
 *         city: "Makati City"
 *         address: "Third Floor, Century City Mall, Kalayaan Avenue, Poblacion"
 *         cuisines: "French, Japanese, Desserts"
 *         average_cost_for_two: 1100
 *         currency: "PHP"
 *         has_table_booking: true
 *         has_online_delivery: false
 *         aggregate_rating: 4.8
 *         votes: 314
 */

/**
 * @swagger
 * /api/restaurants:
 *   get:
 *     summary: Get all restaurants
 *     tags: [Restaurants]
 *     parameters:
 *       - in: query
 *         name: limit
 *         schema:
 *           type: number
 *         description: "Maximum number of restaurants to return. Default value: 10."
 *     responses:
 *       200:
 *         description: List of restaurants retrieved successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Restaurant'
 */
router.get("/", restaurantController.getRestaurants);

/**
 * @swagger
 * /api/restaurants/nearby:
 *   get:
 *     summary: Get nearby restaurants
 *     tags: [Restaurants]
 *     parameters:
 *       - in: query
 *         name: lng
 *         schema:
 *           type: number
 *           default: 1.82446 # Example: Mexico City
 *         required: true
 *         description: Longitude of the user's location.
 *       - in: query
 *         name: lat
 *         schema:
 *           type: number
 *           default: 45.64261  # Example: Mexico City
 *         required: true
 *         description: Latitude of the user's location.
 *       - in: query
 *         name: maxDistance
 *         schema:
 *           type: number
 *           default: 5000
 *         description: Maximum distance in meters (default is 5000m).
 *     responses:
 *       200:
 *         description: List of nearby restaurants retrieved successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Restaurant'
 */
router.get("/nearby", restaurantController.getNearbyRestaurants);

/**
 * @swagger
 * /api/restaurants/getById/{id}:
 *   get:
 *     summary: Get a restaurant by ID
 *     tags: [Restaurants]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: ID of the restaurant to retrieve.
 *     responses:
 *       200:
 *         description: Restaurant retrieved successfully.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Restaurant'
 *       404:
 *         description: Restaurant not found.
 */
router.get("/getById/:id", restaurantController.getRestaurantById);

/**
 * @swagger
 * /api/restaurants:
 *   post:
 *     summary: Create a new restaurant
 *     tags: [Restaurants]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Restaurant'
 *     responses:
 *       201:
 *         description: Restaurant created successfully.
 *       500:
 *         description: Error creating the restaurant.
 */
router.post("/", restaurantController.createRestaurant);

/**
 * @swagger
 * /api/restaurants/update/{id}:
 *   put:
 *     summary: Update a restaurant
 *     tags: [Restaurants]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: Restaurant ID.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Restaurant'
 *     responses:
 *       200:
 *         description: Restaurant updated successfully.
 *       404:
 *         description: Restaurant not found.
 */
router.put("/update/:id", restaurantController.updateRestaurant);

/**
 * @swagger
 * /api/restaurants/delete/{id}:
 *   delete:
 *     summary: Delete a restaurant
 *     tags: [Restaurants]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *         description: Restaurant ID.
 *     responses:
 *       200:
 *         description: Restaurant deleted successfully.
 *       404:
 *         description: Restaurant not found.
 */
router.delete("delete/:id", restaurantController.deleteRestaurant);

module.exports = router;
